PianoMelody.Web/Controllers/InfoController.cs
namespace PianoMelody.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;
    using OrangeJetpack.Localization;

    using Helpers;
    using Models.BindingModels;
    using Models.ViewModels;

    using PianoMelody.Helpers;
    using PianoMelody.Models;

    [Authorize(Roles = "Admin")]
    public class InfoController : BaseController
    {
        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            if (page < 1)
            {
                return this.RedirectToAction("Index");
            }

            var model = new InfoWithPager();
            var pager = new Pager(this.Data.Informations.GetAll().Count(), page);
            model.Pager = pager;

            var informations = this.Data.Informations.GetAll()
                                                     .OrderBy(i => i.Position)
                                                     .Skip((pager.CurrentPage - 1) * pager.PageSize)
                                                     .Take(pager.PageSize)
                                                     .ProjectTo<InfoViewModel>()
                                                     .Localize(this.CurrentCulture, i => i.Title, i => i.Content);
            model.Informations = informations;
            return View(model);
        }

        public ActionResult Create(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string returnUrl, InfoBindingModel infoBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var multimedia = MultimediaHelper.CreateSingle(this.Server, infoBindingModel.Multimedia, this.GetBaseUrl());
            if (multimedia != null)
            {
                this.Data.Multimedia.Add(multimedia);
            }

            var info = new Information()
            {
                Created = DateTime.Now,
                Title = JsonHelper.Serialize(infoBindingModel.EnTitle, infoBindingModel.RuTitle, infoBindingModel.BgTitle),
                Content = JsonHelper.Serialize(infoBindingModel.EnContent, infoBindingModel.RuContent, infoBindingModel.BgContent),
                Multimedia = multimedia
            };

            this.Data.Informations.Add(info);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Edit(int id, string returnUrl)
        {
            var currentInfo = this.Data.Informations.Find(id);
            if (currentInfo == null)
            {
                return Redirect(returnUrl);
            }

            var titleLocs = JsonHelper.Deserialize(currentInfo.Title);
            var contentLocs = JsonHelper.Deserialize(currentInfo.Content);

            var editInfo = new InfoBindingModel()
            {
                EnTitle = titleLocs[0].v,
                RuTitle = titleLocs[1].v,
                BgTitle = titleLocs[2].v,
                EnContent = contentLocs[0].v,
                RuContent = contentLocs[1].v,
                BgContent = contentLocs[2].v
            };

            if (currentInfo.Multimedia != null)
            {
                editInfo.Url = currentInfo.Multimedia.Url;
            }

            return View(editInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, string returnUrl, InfoBindingModel infoBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentInfo = this.Data.Informations.Find(id);
            if (currentInfo == null)
            {
                return this.View();
            }

            if (infoBindingModel.Multimedia != null)
            {
                if (currentInfo.Multimedia != null)
                {
                    MultimediaHelper.DeleteSingle(this.Server, currentInfo.Multimedia);
                    this.Data.Multimedia.Delete(currentInfo.Multimedia);
                }

                currentInfo.Multimedia = MultimediaHelper.CreateSingle(this.Server, infoBindingModel.Multimedia, this.GetBaseUrl());
            }

            currentInfo.Title = JsonHelper.Serialize(infoBindingModel.EnTitle, infoBindingModel.RuTitle, infoBindingModel.BgTitle);
            currentInfo.Content = JsonHelper.Serialize(infoBindingModel.EnContent, infoBindingModel.RuContent, infoBindingModel.BgContent);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Delete(int id, string returnUrl)
        {
            var deleteInfo = this.Data.Informations.GetAll().ProjectTo<InfoViewModel>()
                                                            .FirstOrDefault(i => i.Id == id)
                                                            .Localize(this.CurrentCulture, i => i.Title, i => i.Content);
            if (deleteInfo == null)
            {
                return Redirect(returnUrl);
            }

            return View(deleteInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string returnUrl, InfoViewModel infoViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentInfo = this.Data.Informations.Find(id);
            if (currentInfo == null)
            {
                return this.View();
            }

            if (currentInfo.Multimedia != null)
            {
                MultimediaHelper.DeleteSingle(this.Server, currentInfo.Multimedia);
                this.Data.Multimedia.Delete(currentInfo.Multimedia);
            }

            this.Data.Informations.Delete(currentInfo);

            this.Data.SaveChanges();

            this.RePosition();

            return Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Up(int id, string returnUrl)
        {
            var up = this.Data.Informations.Find(id);
            if (up != null)
            {
                var down = this.Data.Informations.GetAll().FirstOrDefault(p => p.Position == up.Position - 1);
                if (down != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Down(int id, string returnUrl)
        {
            var down = this.Data.Informations.Find(id);
            if (down != null)
            {
                var up = this.Data.Informations.GetAll().FirstOrDefault(p => p.Position == down.Position + 1);
                if (up != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        private void RePosition()
        {
            var informations = this.Data.Informations.GetAll().OrderBy(a => a.Position).ToList();

            for (int i = 0; i < informations.Count; i++)
            {
                informations[i].Position = i + 1;
            }

            this.Data.SaveChanges();
        }
    }
}

PianoMelody.Web/Controllers/NewsController.cs
namespace PianoMelody.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;
    using OrangeJetpack.Localization;

    using Helpers;
    using Models.BindingModels;
    using Models.ViewModels;

    using PianoMelody.Helpers;
    using PianoMelody.Models;

    [Authorize(Roles = "Admin")]
    public class NewsController : BaseController
    {
        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            if (page < 1)
            {
                return this.RedirectToAction("Index");
            }

            var model = new NewsWithPager();
            var pager = new Pager(this.Data.News.GetAll().Count(), page);
            model.Pager = pager;

            var news = this.Data.News.GetAll()
                                     .OrderByDescending(n => n.Created)
                                     .Skip((pager.CurrentPage - 1) * pager.PageSize)
                                     .Take(pager.PageSize)
                                     .ProjectTo<NewsViewModel>()
                                     .Localize(this.CurrentCulture, n => n.Title, n => n.Content);
            model.News = news;
            return View(model);
        }

        public ActionResult Create(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string returnUrl, NewsBindingModel newsBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var multimedia = MultimediaHelper.CreateSingle(this.Server, newsBindingModel.Multimedia, this.GetBaseUrl());
            if (multimedia != null)
            {
                this.Data.Multimedia.Add(multimedia);
            }

            var news = new News()
            {
                Created = DateTime.Now,
                Title = JsonHelper.Serialize(newsBindingModel.EnTitle, newsBindingModel.RuTitle, newsBindingModel.BgTitle),
                Content = JsonHelper.Serialize(newsBindingModel.EnContent, newsBindingModel.RuContent, newsBindingModel.BgContent),
                Multimedia = multimedia
            };

            this.Data.News.Add(news);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Edit(int id, string returnUrl)
        {
            var currentNews = this.Data.News.Find(id);
            if (currentNews == null)
            {
                return Redirect(returnUrl);
            }

            var titleLocs = JsonHelper.Deserialize(currentNews.Title);
            var contentLocs = JsonHelper.Deserialize(currentNews.Content);

            var editNews = new NewsBindingModel()
            {
                Created = currentNews.Created,
                EnTitle = titleLocs[0].v,
                RuTitle = titleLocs[1].v,
                BgTitle = titleLocs[2].v,
                EnContent = contentLocs[0].v,
                RuContent = contentLocs[1].v,
                BgContent = contentLocs[2].v,
            };

            if (currentNews.Multimedia != null)
            {
                editNews.Url = currentNews.Multimedia.Url;
            }

            return View(editNews);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, string returnUrl, NewsBindingModel newsBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentNews = this.Data.News.Find(id);
            if (currentNews == null)
            {
                return this.View();
            }

            if (newsBindingModel.Multimedia != null)
            {
                if (currentNews.Multimedia != null)
                {
                    MultimediaHelper.DeleteSingle(this.Server, currentNews.Multimedia);
                    this.Data.Multimedia.Delete(currentNews.Multimedia);
                }

                currentNews.Multimedia = MultimediaHelper.CreateSingle(this.Server, newsBindingModel.Multimedia, this.GetBaseUrl());
            }

            currentNews.Created = newsBindingModel.Created;
            currentNews.Title = JsonHelper.Serialize(newsBindingModel.EnTitle, newsBindingModel.RuTitle, newsBindingModel.BgTitle);
            currentNews.Content = JsonHelper.Serialize(newsBindingModel.EnContent, newsBindingModel.RuContent, newsBindingModel.BgContent);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Delete(int id, string returnUrl)
        {
            var deleteNews = this.Data.News.GetAll().ProjectTo<NewsViewModel>()
                                                    .FirstOrDefault(n => n.Id == id)
                                                    .Localize(this.CurrentCulture, n => n.Title, n => n.Content);
            if (deleteNews == null)
            {
                return Redirect(returnUrl);
            }

            return View(deleteNews);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string returnUrl, NewsViewModel newsViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentNews = this.Data.News.Find(id);
            if (currentNews == null)
            {
                return this.View();
            }

            if (currentNews.Multimedia != null)
            {
                MultimediaHelper.DeleteSingle(this.Server, currentNews.Multimedia);
                this.Data.Multimedia.Delete(currentNews.Multimedia);
            }

            this.Data.News.Delete(currentNews);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }
    }
}

PianoMelody.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="@CultureHelper.GetCurrentNeutralCulture()" dir="@(CultureHelper.IsRightToLeft() ? "rtl" : "ltr")">
<head>
    <title>@ViewBag.Title - @Resources.Logo</title>
    <meta charset="utf-8" lang="@CultureHelper.GetCurrentNeutralCulture()" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <link rel="alternate" hreflang="@CultureHelper.GetCurrentNeutralCulture()" href="@Request.Url" />
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,700|Tenor+Sans" rel="stylesheet" ">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-85089618-1', 'auto');
      ga('send', 'pageview');
    </script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7&appId=1063382997006782";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <header>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(Resources.Logo, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Resources.Products <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink(Resources.Promotions, "Promotions", "Products")</li>
                                @{
                                    Html.RenderAction("Menu", "Products");
                                }
                                <li>@Html.ActionLink(Resources.All, "Index", "Products")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink(Resources.Services, "Index", "Services")</li>
                        <li>@Html.ActionLink(Resources.Info, "Index", "Info")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Resources.About <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink(Resources.About, "About", "Home")</li>
                                <li>@Html.ActionLink(Resources.Gallery, "Index", "Gallery")</li>
                                <li>@Html.ActionLink(Resources.News, "Index", "News")</li>
                                <li>@Html.ActionLink(Resources.References, "Index", "References")</li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Contact", "Home")">@Resources.Contacts <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></a></li>
                        @Html.Partial("_SwitchLanguage")
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <main class="cd-main-content container body-content background">
        @Html.Partial("_Notifications")
        @RenderBody()
    </main>

    <footer class="fluid">
        <div class="container">
            <div class="col-lg-4 links">
                <ul>
                    <li>@Html.ActionLink(Resources.About, "About", "Home")</li>
                    <li>@Html.ActionLink(Resources.Services, "Index", "Services")</li>
                    <li>@Html.ActionLink(Resources.Info, "Index", "Info")</li>
                    <li>@Html.ActionLink(Resources.News, "Index", "News")</li>
                    <li>@Html.ActionLink(Resources.Contacts, "Contact", "Home")</li>
                </ul>
            </div>
            <div class="col-lg-4 text-center ">
                <div>
                    <div class="fb-like" data-href="https://www.facebook.com/%D0%9F%D0%B8%D0%B0%D0%BD%D0%BE-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%9C%D0%95%D0%9B%D0%9E%D0%94%D0%98%D0%AF-%D0%9F%D0%98%D0%90%D0%9D%D0%90-%D0%B8-%D0%A0%D0%9E%D0%AF%D0%9B%D0%98-Piano-store-Melody-119361421463741/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                </div>
                <div>
                    <a href="https://twitter.com/melodiaeood" class="twitter-follow-button" data-show-count="false">Follow @@melodiaeood</a>
                    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
                <div class="social">
                    <a href="https://www.facebook.com/%D0%9F%D0%B8%D0%B0%D0%BD%D0%BE-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%9C%D0%95%D0%9B%D0%9E%D0%94%D0%98%D0%AF-%D0%9F%D0%98%D0%90%D0%9D%D0%90-%D0%B8-%D0%A0%D0%9E%D0%AF%D0%9B%D0%98-Piano-store-Melody-119361421463741/" rel="alternate" target="_blank"><img src="~/Images/facebook.png" class="social-icon" /></a>
                    <a href="https://twitter.com/melodiaeood" rel="alternate" target="_blank"><img src="~/Images/twitter.png" class="social-icon" /></a>
                    <a href="https://plus.google.com/105912479979767940315" rel="alternate" target="_blank"><img src="~/Images/google-plus.png" class="social-icon" /></a>
                    <a href="https://www.pinterest.com/pin/147563325269810817/" rel="alternate" target="_blank"><img src="~/Images/pinterest.png" class="social-icon" /></a>
                </div>
            </div>
            <div class="col-lg-4 text-center language">
                <div class="row">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.Partial("_LoginPartial")
                    }
                    else
                    {
                        <p class="copyright">@Resources.Logo &copy; 2016 - @DateTime.Now.Year</p>
                    }
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/shared")
    @RenderSection("scripts", required: false)
</body>
</html>

PianoMelody.Web/Views/Shared/_Notifications.cshtml
@using PianoMelody.Web.Extensions
@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if (errorList.Count() > 1)
        {
            <strong><span class="glyphicon glyphicon-remove"></span></strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else
        {
            <strong><span class="glyphicon glyphicon-remove"></span></strong>
            @Html.Raw(errorList.First())
        }
    </div>
}
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if (warningList.Count() > 1)
        {
            <strong><span class="glyphicon glyphicon-warning-sign"></span></strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else
        {
            <strong><span class="glyphicon glyphicon-warning-sign"></span></strong>
            @Html.Raw(warningList.First())
        }
    </div>
}
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if (successList.Count() > 1)
        {
            <strong><span class="glyphicon glyphicon-ok"></span></strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else
        {
            <strong><span class="glyphicon glyphicon-ok"></span></strong>
            @Html.Raw(successList.First())
        }
    </div>
}
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if (infoList.Count() > 1)
        {
            <strong><span class="glyphicon glyphicon-info-sign"></span></strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else
        {
            <strong><span class="glyphicon glyphicon-info-sign"></span></strong>
            @Html.Raw(infoList.First())
        }
    </div>
}

PianoMelody.Web/Views/Shared/_Pager.cshtml
@{ 
    var group = Request.Params["group"];
    var manufacturer = Request.Params["manufacturer"];
    var condition = Request.Params["condition"];
}

@if (Model.EndPage > 1)
{
    <div class="col-lg-4 col-md-4">
        <ul class="pagination">
            @if (Model.CurrentPage > 1)
            {
                <li>
                    <a href="@Url.Action("Index", new { group = group, manufacturer = manufacturer, condition = condition, page = Model.CurrentPage - 1 })" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (var page = Model.StartPage; page <= Model.EndPage; page++)
            {
                <li class="@(page == Model.CurrentPage ? "active" : "")">
                    <a href="@Url.Action("Index", new { group = group, manufacturer = manufacturer, condition = condition, page = @page })">@page</a>
                </li>
            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li>
                    <a href="@Url.Action("Index", new { group = group, manufacturer = manufacturer, condition = condition, page = Model.CurrentPage + 1 })" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </div>
}

PianoMelody.Web/Views/Shared/_PhotoSwipeRoot.cshtml
<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

    <!-- Background of PhotoSwipe.
         It's a separate element, as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>

    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">

        <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
        <!-- don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <!--  Controls are self-explanatory. Order can be changed. -->

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                <button class="pswp__button pswp__button--share" title="Share"></button>

                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
            </div>

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>

            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>

            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>

        </div>

    </div>

</div>

PianoMelody.Web/Views/Shared/_SwitchLanguage.cshtml
@{
    string CurrentUrl = Request.RawUrl.ToString();
    string EnUrl = "/en";
    string BgUrl = "";
    string RuUrl = "/ru";

    if (CurrentUrl.Length >= 3)
    {
        EnUrl = "/en" + CurrentUrl.Substring(3);
        BgUrl = "/bg" + CurrentUrl.Substring(3);
        RuUrl = "/ru" + CurrentUrl.Substring(3);
    }

    string languageImage = "/Images/" + CultureHelper.GetCurrentNeutralCulture() + ".png";
}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="@languageImage" alt="@CultureHelper.GetCurrentNeutralCulture()" /><span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <li>
            <a href='@BgUrl'>
                <img src='@Url.Content("~/Images/bg.png")' /> Български
            </a>
        </li>
        <li>
            <a href='@EnUrl'>
                <img src='@Url.Content("~/Images/en.png")' /> English
            </a>
        </li>
        <li>
            <a href='@RuUrl'>
                <img src='@Url.Content("~/Images/ru.png")' /> Русский
            </a>
        </li>
    </ul>
</li>