PianoMelody.Web/Models/ViewModels/ReferenceViewModel.cs
using OrangeJetpack.Localization;
using PianoMelody.Helpers;
using PianoMelody.Models;
using PianoMelody.Web.Contracts;
using System;
using System.Collections.Generic;

namespace PianoMelody.Web.Models.ViewModels
{
    public class ReferenceViewModel : IMapFrom<Reference>, ILocalizable
    {
        public int Id { get; set; }

        public int Position { get; set; }

        public DateTime Created { get; set; }

        [Localized]
        public string Title { get; set; }

        [Localized]
        public string Content { get; set; }

        public Multimedia Multimedia { get; set; }
    }

    public class ReferencesWithPager
    {
        public IEnumerable<ReferenceViewModel> References { get; set; }

        public Pager Pager { get; set; }
    }
}

PianoMelody.Web/Controllers/ReferencesController.cs
namespace PianoMelody.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;
    using OrangeJetpack.Localization;

    using Helpers;
    using Models.BindingModels;
    using Models.ViewModels;

    using PianoMelody.Helpers;
    using PianoMelody.Models;

    [Authorize(Roles = "Admin")]
    public class ReferencesController : BaseController
    {
        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            if (page < 1)
            {
                return this.RedirectToAction("Index");
            }

            var model = new ReferencesWithPager();
            var pager = new Pager(this.Data.References.GetAll().Count(), page);
            model.Pager = pager;

            var references = this.Data.References.GetAll()
                                                 .OrderBy(r => r.Position)
                                                 .Skip((pager.CurrentPage - 1) * pager.PageSize)
                                                 .Take(pager.PageSize)
                                                 .ProjectTo<ReferenceViewModel>()
                                                 .Localize(this.CurrentCulture, r => r.Title, r => r.Content);
            model.References = references;
            return View(model);
        }

        public ActionResult Create(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string returnUrl, ReferenceBindingModel referenceBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var multimedia = MultimediaHelper.CreateSingle(this.Server, referenceBindingModel.Multimedia, this.GetBaseUrl());
            if (multimedia != null)
            {
                this.Data.Multimedia.Add(multimedia);
            }

            var reference = new Reference()
            {
                Created = DateTime.Now,
                Title = JsonHelper.Serialize(referenceBindingModel.EnTitle, referenceBindingModel.RuTitle, referenceBindingModel.BgTitle),
                Content = JsonHelper.Serialize(referenceBindingModel.EnContent, referenceBindingModel.RuContent, referenceBindingModel.BgContent),
                Multimedia = multimedia
            };

            this.Data.References.Add(reference);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Edit(int id, string returnUrl)
        {
            var currentReference = this.Data.References.Find(id);
            if (currentReference == null)
            {
                return Redirect(returnUrl);
            }

            var titleLocs = JsonHelper.Deserialize(currentReference.Title);
            var contentLocs = JsonHelper.Deserialize(currentReference.Content);

            var editReference = new ReferenceBindingModel()
            {
                EnTitle = titleLocs[0].v,
                RuTitle = titleLocs[1].v,
                BgTitle = titleLocs[2].v,
                EnContent = contentLocs[0].v,
                RuContent = contentLocs[1].v,
                BgContent = contentLocs[2].v
            };

            if (currentReference.Multimedia != null)
            {
                editReference.Url = currentReference.Multimedia.Url;
            }

            return View(editReference);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, string returnUrl, ReferenceBindingModel referenceBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentReference = this.Data.References.Find(id);
            if (currentReference == null)
            {
                return this.View();
            }

            if (referenceBindingModel.Multimedia != null)
            {
                if (currentReference.Multimedia != null)
                {
                    MultimediaHelper.DeleteSingle(this.Server, currentReference.Multimedia);
                    this.Data.Multimedia.Delete(currentReference.Multimedia);
                }

                currentReference.Multimedia = MultimediaHelper.CreateSingle(this.Server, referenceBindingModel.Multimedia, this.GetBaseUrl());
            }

            currentReference.Title = JsonHelper.Serialize(referenceBindingModel.EnTitle, referenceBindingModel.RuTitle, referenceBindingModel.BgTitle);
            currentReference.Content = JsonHelper.Serialize(referenceBindingModel.EnContent, referenceBindingModel.RuContent, referenceBindingModel.BgContent);

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Delete(int id, string returnUrl)
        {
            var deleteReference = this.Data.References.GetAll().ProjectTo<ReferenceViewModel>()
                                                               .FirstOrDefault(r => r.Id == id)
                                                               .Localize(this.CurrentCulture, r => r.Title, r => r.Content);
            if (deleteReference == null)
            {
                return Redirect(returnUrl);
            }

            return View(deleteReference);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string returnUrl, ReferenceViewModel referenceViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentReference = this.Data.References.Find(id);
            if (currentReference == null)
            {
                return this.View();
            }

            if (currentReference.Multimedia != null)
            {
                MultimediaHelper.DeleteSingle(this.Server, currentReference.Multimedia);
                this.Data.Multimedia.Delete(currentReference.Multimedia);
            }

            this.Data.References.Delete(currentReference);

            this.Data.SaveChanges();

            this.RePosition();

            return Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Up(int id, string returnUrl)
        {
            var up = this.Data.References.Find(id);
            if (up != null)
            {
                var down = this.Data.References.GetAll().FirstOrDefault(p => p.Position == up.Position - 1);
                if (down != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Down(int id, string returnUrl)
        {
            var down = this.Data.References.Find(id);
            if (down != null)
            {
                var up = this.Data.References.GetAll().FirstOrDefault(p => p.Position == down.Position + 1);
                if (up != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        private void RePosition()
        {
            var references = this.Data.References.GetAll().OrderBy(a => a.Position).ToList();

            for (int i = 0; i < references.Count; i++)
            {
                references[i].Position = i + 1;
            }

            this.Data.SaveChanges();
        }
    }
}

PianoMelody.Web/Views/References/Create.cshtml
@model PianoMelody.Web.Models.BindingModels.ReferenceBindingModel

@{
    ViewBag.Title = Resources._CreateNew + " " + Resources._Reference;
}

<h2>@Resources._CreateNew @Resources._Reference</h2>
<hr />

@using (Html.BeginForm("Create", "References", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.EnTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RuTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BgTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RuContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BgContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <img id="image-preview" src="~/Images/no_image.jpg" class="news-image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multimedia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    Browse <input type="file" name="Multimedia" id="file" style="display: none;">
                </label>
                @Html.ValidationMessageFor(model => model.Multimedia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources._CreateNew" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/image-preview")
}

PianoMelody.Web/Views/References/Delete.cshtml
@model PianoMelody.Web.Models.ViewModels.ReferenceViewModel

@{
    ViewBag.Title = Resources._Delete + Resources._Reference;
}

<h3>@Resources._AreYouSure</h3>
<hr />

<article class="panel panel-default">
    @Html.Partial("_ReferenceInfo", Model)

     @if (User.IsInRole("Admin"))
     {
         <div class="panel-footer">
             @using (Html.BeginForm("Delete", "References", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { }))
             {
                 @Html.AntiForgeryToken()

                 <div class="form-actions no-color">
                     <input type="submit" value="@Resources._Delete" class="btn btn-danger" />
                 </div>
             }
         </div>
     }
</article>

PianoMelody.Web/Views/References/Edit.cshtml
@model PianoMelody.Web.Models.BindingModels.ReferenceBindingModel
@{
    ViewBag.Title = Resources._Edit + " " + Resources._Reference;
    var url = "/Images/no_image.jpg";
    if (Model != null && Model.Url != null)
    {
        url = Model.Url;
    }
}
<h2>@Resources._Edit @Resources._Reference</h2>
<hr />
@using (Html.BeginForm("Edit", "References", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.EnTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RuTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BgTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EnContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnContent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RuContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuContent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BgContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <img id="image-preview" src="@url" class="news-image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multimedia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    Browse <input type="file" name="Multimedia" id="file" style="display: none;">
                </label>
                @Html.ValidationMessageFor(model => model.Multimedia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources._Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/image-preview")
}

PianoMelody.Web/Views/References/Index.cshtml
@model PianoMelody.Web.Models.ViewModels.ReferencesWithPager

@{
    ViewBag.Title = Resources.References;
    ViewBag.Description = Resources.ReferencesDescription;
    ViewBag.Keywords = Resources.ReferencesKeywords;
}

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink(Resources._CreateNew, "Create", new { returnUrl = Request.RawUrl }, new { @class = "btn btn-primary" })
    </p>
    <hr />
}

@foreach (var reference in Model.References)
{
    <article class="panel panel-default block">
        @Html.Partial("_ReferenceInfo", reference)

        @if (User.IsInRole("Admin"))
        {
        <div class="panel-footer">
            @using (Html.BeginForm("Up", "References", new { id = reference.Id, returnUrl = Request.RawUrl }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <button type="submit" class="btn btn-success btn-inline">
                    <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
                    @reference.Position
                </button>
            }

            @using (Html.BeginForm("Down", "References", new { id = reference.Id, returnUrl = Request.RawUrl }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <button type="submit" class="btn btn-warning btn-inline">
                    <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    @reference.Position
                </button>
            }

            @Html.ActionLink(Resources._Edit, "Edit", new { id = reference.Id, returnUrl = Request.RawUrl }, new { @class = "btn btn-primary" })
            @Html.ActionLink(Resources._Delete, "Delete", new { id = reference.Id, returnUrl = Request.RawUrl }, new { @class= "btn btn-danger" }) 
        </div>
        }
    </article>
}
<div class="row">
    @Html.Partial("_Pager", Model.Pager)
    @Html.Partial("_PhotoSwipeRoot")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/photoswipe")
    @Scripts.Render("~/bundles/load-gallery")
}

PianoMelody.Web/Views/References/_ReferenceInfo.cshtml
@model PianoMelody.Web.Models.ViewModels.ReferenceViewModel

@{
    var url = "/Images/no_image.jpg";
    var thumb = url;
    var dataSize = "770x400";

    if (Model != null && Model.Multimedia != null)
    {
        url = Model.Multimedia.Url;
        var thumbElements = url.Split('/');
        thumb = string.Format("/{0}/thumbs/{1}", thumbElements[1], thumbElements[2]);
        dataSize = Model.Multimedia.DataSize;
    }
}

<div class="panel-heading">
    @Html.DisplayFor(modelItem => Model.Title)
      </div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-8">
            <p class="ellipsis">
                @Html.DisplayFor(modelItem => Model.Content)
            </p>
        </div>
        <div class="col-lg-4">
            <div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
                <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
                    <a href="@url" itemprop="contentUrl" data-size="@dataSize">
                        <img src="@thumb" itemprop="thumbnail" alt="@Model.Title" />
                    </a>
                </figure>
            </div>
        </div>
    </div>
</div>