PianoMelody.Web/Models/ViewModels/ManufacturerViewModel.cs
using OrangeJetpack.Localization;
using PianoMelody.Helpers;
using PianoMelody.Models;
using PianoMelody.Web.Contracts;
using System.Collections.Generic;

namespace PianoMelody.Web.Models.ViewModels
{
    public class ManufacturerViewModel : IMapFrom<Manufacturer>, ILocalizable
    {
        public int Id { get; set; }

        public int Position { get; set; }

        [Localized]
        public string Name { get; set; }

        public bool AreWeAgent { get; set; }

        public string UrlAddress { get; set; }

        public Multimedia Multimedia { get; set; }
    }

    public class ManufacturersWithPager
    {
        public IEnumerable<ManufacturerViewModel> Manufacturers { get; set; }

        public Pager Pager { get; set; }
    }
}

PianoMelody.Web/Controllers/ManufacturerController.cs
namespace PianoMelody.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;
    using OrangeJetpack.Localization;

    using Helpers;
    using Models.BindingModels;
    using Models.ViewModels;

    using PianoMelody.Helpers;
    using PianoMelody.Models;

    [Authorize(Roles = "Admin")]
    public class ManufacturerController : BaseController
    {
        public ActionResult Index(int page = 1)
        {
            if (page < 1)
            {
                return this.RedirectToAction("Index");
            }

            var model = new ManufacturersWithPager();
            var pager = new Pager(this.Data.Manufacturers.GetAll().Count(), page);
            model.Pager = pager;

            var manufacturers = this.Data.Manufacturers.GetAll()
                                                       .OrderBy(m => m.Position)
                                                       .Skip((pager.CurrentPage - 1) * pager.PageSize)
                                                       .Take(pager.PageSize)
                                                       .ProjectTo<ManufacturerViewModel>()
                                                       .Localize(this.CurrentCulture, m => m.Name);
            model.Manufacturers = manufacturers;
            return View(model);
        }

        public ActionResult Create(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string returnUrl, ManufacturerBindingModel manufacturerBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var multimedia = MultimediaHelper.CreateSingle(this.Server, manufacturerBindingModel.Multimedia, this.GetBaseUrl());
            if (multimedia != null)
            {
                this.Data.Multimedia.Add(multimedia);
            }

            var manufacturer = new Manufacturer()
            {
                Name = JsonHelper.Serialize(manufacturerBindingModel.EnName, manufacturerBindingModel.RuName, manufacturerBindingModel.BgName),
                AreWeAgent = manufacturerBindingModel.AreWeAgent,
                UrlAddress = manufacturerBindingModel.UrlAddress,
                Multimedia = multimedia
            };

            this.Data.Manufacturers.Add(manufacturer);
            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Edit(int id, string returnUrl)
        {
            var currentManufacturer = this.Data.Manufacturers.Find(id);
            if (currentManufacturer == null)
            {
                return Redirect(returnUrl);
            }

            var nameLocs = JsonHelper.Deserialize(currentManufacturer.Name);

            var editManufacturer = new ManufacturerBindingModel()
            {
                EnName = nameLocs[0].v,
                RuName = nameLocs[1].v,
                BgName = nameLocs[2].v,
                AreWeAgent = currentManufacturer.AreWeAgent,
                UrlAddress = currentManufacturer.UrlAddress
            };

            if (currentManufacturer.Multimedia != null)
            {
                editManufacturer.Url = currentManufacturer.Multimedia.Url;
            }

            return View(editManufacturer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, string returnUrl, ManufacturerBindingModel manufacturerBindingModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentManufacturer = this.Data.Manufacturers.Find(id);
            if (currentManufacturer == null)
            {
                return this.View();
            }

            if (manufacturerBindingModel.Multimedia != null)
            {
                if (currentManufacturer.Multimedia != null)
                {
                    MultimediaHelper.DeleteSingle(this.Server, currentManufacturer.Multimedia);
                    this.Data.Multimedia.Delete(currentManufacturer.Multimedia);
                }

                currentManufacturer.Multimedia = MultimediaHelper.CreateSingle(this.Server, manufacturerBindingModel.Multimedia, this.GetBaseUrl());
            }

            currentManufacturer.Name = JsonHelper.Serialize(manufacturerBindingModel.EnName, manufacturerBindingModel.RuName, manufacturerBindingModel.BgName);
            currentManufacturer.AreWeAgent = manufacturerBindingModel.AreWeAgent;
            currentManufacturer.UrlAddress = manufacturerBindingModel.UrlAddress;

            this.Data.SaveChanges();

            return Redirect(returnUrl);
        }

        public ActionResult Delete(int id, string returnUrl)
        {
            var deleteManufacturer = this.Data.Manufacturers.GetAll().ProjectTo<ManufacturerViewModel>()
                                                                     .FirstOrDefault(m => m.Id == id)
                                                                     .Localize(this.CurrentCulture, m => m.Name);
            if (deleteManufacturer == null)
            {
                return Redirect(returnUrl);
            }

            return View(deleteManufacturer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string returnUrl, ManufacturerViewModel manufacturerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var currentManufacturer = this.Data.Manufacturers.Find(id);
            if (currentManufacturer == null)
            {
                return this.View();
            }

            if (currentManufacturer.Multimedia != null)
            {
                MultimediaHelper.DeleteSingle(this.Server, currentManufacturer.Multimedia);
                this.Data.Multimedia.Delete(currentManufacturer.Multimedia);
            }

            this.Data.Manufacturers.Delete(currentManufacturer);

            this.Data.SaveChanges();

            this.RePosition();

            return Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Up(int id, string returnUrl)
        {
            var up = this.Data.Manufacturers.Find(id);
            if (up != null)
            {
                var down = this.Data.Manufacturers.GetAll().FirstOrDefault(p => p.Position == up.Position - 1);
                if (down != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Down(int id, string returnUrl)
        {
            var down = this.Data.Manufacturers.Find(id);
            if (down != null)
            {
                var up = this.Data.Manufacturers.GetAll().FirstOrDefault(p => p.Position == down.Position + 1);
                if (up != null)
                {
                    int temp = up.Position;
                    up.Position = down.Position;
                    down.Position = temp;

                    this.Data.SaveChanges();
                }
            }

            return this.Redirect(returnUrl);
        }

        private void RePosition()
        {
            var manufacturers = this.Data.Manufacturers.GetAll().OrderBy(a => a.Position).ToList();

            for (int i = 0; i < manufacturers.Count; i++)
            {
                manufacturers[i].Position = i + 1;
            }

            this.Data.SaveChanges();
        }
    }
}

PianoMelody.Web/Views/Manufacturer/Create.cshtml
@model PianoMelody.Web.Models.BindingModels.ManufacturerBindingModel

@{
    ViewBag.Title = Resources._CreateNew + " " + Resources._Manufacturer;
}

<h2>@Resources._CreateNew @Resources._Manufacturer</h2>
<hr />

@using (Html.BeginForm("Create", "Manufacturer", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.EnName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RuName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BgName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreWeAgent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AreWeAgent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AreWeAgent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <img id="image-preview" src="~/Images/no_image.jpg" class="news-image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multimedia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    Browse <input type="file" name="Multimedia" id="file" style="display: none;">
                </label>
                @Html.ValidationMessageFor(model => model.Multimedia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources._CreateNew" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/image-preview")
}

PianoMelody.Web/Views/Manufacturer/Delete.cshtml
@model PianoMelody.Web.Models.ViewModels.ManufacturerViewModel

@{
    ViewBag.Title = Resources._Delete + Resources._Manufacturer;
}

<h3>@Resources._AreYouSure</h3>
<hr />

<article class="panel panel-default">
    @Html.Partial("_ManufacturerInfo", Model)

     @if (User.IsInRole("Admin"))
     {
         <div class="panel-footer">
             @using (Html.BeginForm("Delete", "Manufacturer", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { }))
             {
                 @Html.AntiForgeryToken()

                 <div class="form-actions no-color">
                     <input type="submit" value="@Resources._Delete" class="btn btn-danger" />
                 </div>
             }
         </div>
     }
</article>

PianoMelody.Web/Views/Manufacturer/Edit.cshtml
@model PianoMelody.Web.Models.BindingModels.ManufacturerBindingModel
@{
    ViewBag.Title = Resources._Edit + " " + Resources._Manufacturer;
    var url = "/Images/no_image.jpg";
    if (Model != null && Model.Url != null)
    {
        url = Model.Url;
    }
}
<h2>@Resources._Edit @Resources._Manufacturer</h2>
<hr />
@using (Html.BeginForm("Edit", "Manufacturer", new { returnUrl = this.Request.QueryString["returnUrl"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.EnName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RuName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BgName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BgName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BgName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AreWeAgent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AreWeAgent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AreWeAgent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UrlAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <img id="image-preview" src="@url" class="news-image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multimedia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="btn btn-default btn-file">
                    Browse <input type="file" name="Multimedia" id="file" style="display: none;">
                </label>
                @Html.ValidationMessageFor(model => model.Multimedia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources._Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/image-preview")
}

PianoMelody.Web/Views/Manufacturer/Index.cshtml
@model PianoMelody.Web.Models.ViewModels.ManufacturersWithPager

@{
    ViewBag.Title = Resources._Manufacturers;
}

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink(Resources._CreateNew, "Create", new { returnUrl = Request.RawUrl }, new { @class = "btn btn-primary" })
    </p>
    <hr />
}

@foreach (var manufacturer in Model.Manufacturers)
{
    <article class="panel panel-default">
        @Html.Partial("_ManufacturerInfo", manufacturer)

        @if (User.IsInRole("Admin"))
        {
            <div class="panel-footer">
                @using (Html.BeginForm("Up", "Manufacturer", new { id = manufacturer.Id, returnUrl = Request.RawUrl }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <button type="submit" class="btn btn-success btn-inline">
                        <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
                        @manufacturer.Position
                    </button>
                }

                @using (Html.BeginForm("Down", "Manufacturer", new { id = manufacturer.Id, returnUrl = Request.RawUrl }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <button type="submit" class="btn btn-warning btn-inline">
                        <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                        @manufacturer.Position
                    </button>
                }

                @Html.ActionLink(Resources._Edit, "Edit", new { id = manufacturer.Id, returnUrl = Request.RawUrl }, new { @class = "btn btn-primary" })
                @Html.ActionLink(Resources._Delete, "Delete", new { id = manufacturer.Id, returnUrl = Request.RawUrl }, new { @class = "btn btn-danger" })
            </div>
        }
    </article>
}
<div class="row">
    @Html.Partial("_Pager", Model.Pager)
</div>

PianoMelody.Web/Views/Manufacturer/_ManufacturerInfo.cshtml
@model PianoMelody.Web.Models.ViewModels.ManufacturerViewModel

@{
    var url = "/Images/no_image.jpg";
    var thumb = url;

    if (Model != null && Model.Multimedia != null)
    {
        url = Model.Multimedia.Url;
        var thumbElements = url.Split('/');
        thumb = string.Format("/{0}/thumbs/{1}", thumbElements[1], thumbElements[2]);
    }
}

<div class="panel-heading">
    @Html.DisplayFor(modelItem => Model.Name)
</div>
<div class="panel-body">
    <p>
        <a href="@Model.UrlAddress" target="_blank" rel="alternate"><img src="@thumb" itemprop="thumbnail" alt="@Model.Name" /></a>
    </p>
    @Html.DisplayFor(modelItem => Model.AreWeAgent)
</div>